name: dyndown
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - python-dotenv
  - cartopy
  - gdal
  - wrf-python
  - python-cdo
  - geopandas
  - rioxarray
  - ipywidgets
  - jupyterlab
  - nb-clean
  - pylint
  - pytest
  - requests
  - seaborn
  - siphon
  - wget
  - dask
  - cfgrib
  - flake8
  - pip
  - pip:
    - "--editable git@github.com:AlaskaFireWeather/fiweps.git"
  