name: dyndown
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - python-dotenv
  - boto3
  - wrf-python
  - cfgrib
  - python-cdo
  - xarray
  - numpy
  - pandas
  - pyarrow
  - netCDF4
  - matplotlib
  - jupyterlab
  - nb-clean
  - pylint
  - flake8
